/*
 * Auto-Generated by NUKE!
 *   http://arbotix.googlecode.com
 */
int hitPoint = 20;
int tgtPlate = 0;
int bearing = 0;
int leftIR = 0;
int rightIR = 0;

void setup(){
    // setup serial
    Serial.begin(38400);    
    
}

void loop(){

  tgtPlate = random(1, 4);
  //bearing  = random(0,3599);
  byte hitPointByte = (byte)(hitPoint & 0xff);
  byte tgtPlateByte = (byte)(tgtPlate & 0xff);
  
  byte lByte = (byte)(bearing & 0xff);
  byte hByte = (byte)(bearing >> 8);
  byte pitch = 0x00;
  byte roll  = 0x00;
  
  int leftIR  = random(0, 1023);  
  int rightIR = random(0, 1023);  
  
  byte lowLeftIR  = (byte) leftIR;
  byte highLeftIR = (byte) (leftIR >> 8);
  
  byte lowRightIR  = (byte) rightIR;
  byte highRightIR = (byte) (rightIR >> 8);
  
  hitPointByte = 0x01;
  tgtPlateByte = 0x02;
  hByte = 0x03;
  lByte = 0x04;
  pitch = 0x05;
  roll = 0x06;
  lowLeftIR = 0x07;
  highLeftIR = 0x08;
  lowRightIR = 0x09;
  highRightIR = 0x0A;
  
  Serial.print("*");   // rbots
  Serial.print("*");   // rbots
  Serial.print(hitPointByte,BIN);   // rbots
  Serial.print(tgtPlateByte,BIN);   // rbots
  Serial.print(hByte,BIN);   // rbots
  Serial.print(lByte,BIN);   // rbots
  Serial.print(pitch,BIN);   // rbots
  Serial.print(roll,BIN);   // rbots
  Serial.print(lowLeftIR,BIN);  // rbots
  Serial.print(highLeftIR,BIN); // rbots
  Serial.print(lowRightIR,BIN); // rbots
  Serial.print(highRightIR,BIN); // rbots

  hitPoint--;
  bearing += 10;
 
 if(hitPoint < 0) {
   hitPoint = 20;
 }
 
 if(bearing > 3599) {
   bearing = 0;
 }
 //Serial.flush();
 delay(5000);
}

