/*
 * Auto-Generated by NUKE!
 *   http://arbotix.googlecode.com
 */

#include <ax12.h>
#include <BioloidController.h>
#include <Commander.h>
#include <avr/pgmspace.h>

//ids for motor are in order M1,M2,..M8

/* min and max positions for each servo */
int mins[] = {432, 424, 482, 483, 440, 488, 413, 485};
int maxs[] = {606, 607, 636, 606, 590, 624, 599, 620};

// pose positions
PROGMEM prog_uint16_t Right_Fwd_Lift[] = {8, 512, 487, 613, 513, 505, 511, 579, 587};
PROGMEM prog_uint16_t Left_Fwd_Lift[] = {8, 510, 510, 510, 574, 509, 604, 511, 510};
PROGMEM prog_uint16_t Left_Fwd_Sweep[] = {8, 510, 444, 502, 586, 564, 574, 567, 505};
PROGMEM prog_uint16_t Left_Fwd_Down[] = {8, 452, 444, 502, 512, 570, 508, 577, 507};
PROGMEM prog_uint16_t Neutral[] = {8, 511, 511, 511, 511, 511, 511, 511, 511};
PROGMEM prog_uint16_t Right_Fwd_Down[] = {8, 568, 545, 502, 504, 460, 518, 435, 511};
PROGMEM prog_uint16_t Right_Fwd_Sweep[] = {8, 586, 587, 616, 503, 484, 520, 433, 600};

Commander command = Commander();
BioloidController bioloid = BioloidController(1000000);

void setup(){
    
    // setup serial
    Serial.begin(38400);
  
    // setup dynamixel turret motors (Az/El)
    ax12SetRegister(13, 24, 1);  // rbots enable torque on az motor
    ax12SetRegister(14, 24, 1);  // rbots enable torque on el motor
    ax12SetRegister2(13, 8, 1023);  // max az CCW angle limit
    ax12SetRegister2(14, 6, 545);  // max el CW angle limit
    ax12SetRegister2(14, 8, 750);  // max el CCW angle limit
    ax12SetRegister2(13, 32, command.goalAzSpeed);  // set az speed
    ax12SetRegister2(14, 32, command.goalElSpeed);  // set el speed
    ax12SetRegister2(13, 30, command.goalAzPos);  // rbots az pos, should have default value at beginning of 511
    ax12SetRegister2(14, 30, command.goalElPos);  // rbots el pos, should have default value at beginning of 600
    
    bioloid.poseSize = 8;
    bioloid.readPose();
    
    // setup neutral position
    bioloid.loadPose(Neutral);
    
    bioloid.interpolateSetup(1000);
    while(bioloid.interpolating > 0){
        bioloid.interpolateStep();
        delay(3);
    }
    
}

void loop(){
      
  if(command.ReadMsgs() > 0){
    
    
    // move azimuth turret
     
    ax12SetRegister2(13, 32, command.goalAzSpeed);  // rbots el vel
    ax12SetRegister2(14, 32, command.goalElSpeed);  // rbots el vel
    ax12SetRegister2(13, 30, command.goalAzPos);  // rbots az pos
    ax12SetRegister2(14, 30, command.goalElPos);  // rbots el pos
    
  }  
}


